#!/usr/bin/python
# -*- coding: iso-8859-15 -*-
import pushover
import time

pushover.init("")
client = pushover.Client("")

w1="/sys/bus/w1/devices/28-000004d4e671/w1_slave"

raw = open(w1, "r").read()
temp = str(float(raw.split("t=")[-1])/1000)
tweet = "Fermentation Temperature: " + temp + "°C\nHeater Status: OFF"
client.send_message(tweet, title="Temperature")
