#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
import sys
import tweepy
import time

CONSUMER_KEY = ''
CONSUMER_SECRET = ''
ACCESS_KEY = ''
ACCESS_SECRET = ''


w1="/sys/bus/w1/devices/28-000004d4e671/w1_slave"

raw = open(w1, "r").read()
temp = str(float(raw.split("t=")[-1])/1000)
tweet = "Fermentation Temperature: " + temp + "°C\nHeater Status: OFF"
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_KEY, ACCESS_SECRET)
api = tweepy.API(auth)
api.update_status(tweet)
